# The expected-servers signal — what SHOULD have attached, versus what did.
#
# `vim.lsp.get_clients` reports only servers that actually attached. Neovim
# exposes no API for the set that was *expected*, so a statusline cannot tell
# "this filetype has no language server" apart from "this filetype's language
# server failed to start". Those render differently: one is normal, the other
# is the signal.
#
# The expected set exists at build time, in cvim's own configuration, and this
# module is what carries it into the runtime. Contract for consumers is
# `inbox/u7-expected-servers-contract.md` in the session directory.
#
# NOTE ON VERIFYING THIS MODULE: with zero servers configured every filetype
# correctly answers "none", so the indicator never firing is exactly what a
# producer that silently does nothing would also produce. Silence is not
# evidence here. Prove it against a deliberately stubbed server entry in
# `lab/lab-lsp.nix`, then remove the stub.
{ config, lib, ... }:
let
  cfg = config.cvim.lsp;

  # Derived from the configuration, never hand-maintained. A `lang` module that
  # lands later is picked up for free, because enabling a server is the same
  # act as appearing in this list.
  #
  # `activate = false` means the server is configured but `vim.lsp.enable()` is
  # never called for it, so it is not expected to attach and does not belong
  # here. `"*"` is nixvim's meta-server holding shared defaults, not a server.
  expected = lib.pipe config.lsp.servers [
    (lib.filterAttrs (name: server: name != "*" && server.enable && server.activate))
    builtins.attrValues
    (map (server: {
      inherit (server) name;
      package = server.package != null;
      fallback = server.packageFallback;
    }))
  ];
in
{
  config = lib.mkIf cfg.enable {
    # A runtime Lua module rather than a global: `require` resolves regardless
    # of init order, so a statusline drawing early never races this layer's
    # `extraConfigLua`. When `cvim.lsp.enable = false` the file is simply
    # absent and `pcall(require, ...)` fails cleanly — that is the degrade
    # path for the `server` profile.
    extraFiles."lua/cvim/lsp.lua".text = ''
      --- What cvim expected to attach to a buffer, and what actually did.
      ---
      --- Generated by modules/lsp/expected-servers.nix. Do not edit.
      local M = {}

      --- Every server cvim enabled AND activated, with its toolchain state.
      --- `package` is true when cvim ships the binary; `fallback` is true when
      --- cvim defers to a $PATH copy (a devshell) before its own.
      local expected = ${lib.nixvim.toLuaObject expected}

      --- filetype -> the subset of `expected` covering it.
      ---
      --- Filled on first ask per filetype, because resolving `vim.lsp.config`
      --- walks the runtimepath to load nvim-lspconfig's `lsp/<name>.lua`. That
      --- must not happen at statusline redraw frequency.
      local by_filetype = {}

      local function servers_for(filetype)
        local hit = by_filetype[filetype]
        if hit then
          return hit
        end

        local found = {}
        for _, server in ipairs(expected) do
          -- An unknown name resolves to nil rather than throwing, so a server
          -- this nvim-lspconfig pin has never heard of covers no filetype
          -- instead of breaking every caller. pcall covers the rarer case of a
          -- malformed `lsp/<name>.lua`.
          local ok, resolved = pcall(function()
            return vim.lsp.config[server.name]
          end)
          local filetypes = ok and resolved and resolved.filetypes or nil
          if filetypes and vim.tbl_contains(filetypes, filetype) then
            found[#found + 1] = server
          end
        end

        by_filetype[filetype] = found
        return found
      end

      --- Attach status for a buffer.
      ---
      --- @param bufnr integer|nil Buffer handle; nil or 0 means the current one.
      --- @return table|nil status Nil only if the buffer handle is invalid.
      ---
      --- status.state is one of:
      ---   "none"     no server is configured for this filetype. Normal.
      ---   "ok"       every expected server attached.
      ---   "partial"  some attached, some did not. THE SIGNAL.
      ---   "missing"  servers were expected and none attached.
      ---
      --- status.expected / status.missing hold `{ name, package, fallback }`
      --- entries; status.attached holds plain client names. Treat all three as
      --- read-only — `expected` is the memoized table, not a copy.
      ---
      --- LSP attach is asynchronous, so a healthy buffer legitimately reports
      --- "missing" for a short window after opening. This reports the truth at
      --- call time and does not smooth that over; redraw on LspAttach and
      --- LspDetach rather than guessing a grace period.
      function M.status(bufnr)
        if bufnr == nil or bufnr == 0 then
          bufnr = vim.api.nvim_get_current_buf()
        end
        if not vim.api.nvim_buf_is_valid(bufnr) then
          return nil
        end

        local want = servers_for(vim.bo[bufnr].filetype)

        local attached, attached_set = {}, {}
        for _, client in ipairs(vim.lsp.get_clients({ bufnr = bufnr })) do
          attached[#attached + 1] = client.name
          attached_set[client.name] = true
        end

        local missing = {}
        for _, server in ipairs(want) do
          if not attached_set[server.name] then
            missing[#missing + 1] = server
          end
        end

        local state
        if #want == 0 then
          state = "none"
        elseif #missing == 0 then
          state = "ok"
        elseif #missing == #want then
          state = "missing"
        else
          state = "partial"
        end

        return {
          state = state,
          expected = want,
          attached = attached,
          missing = missing,
        }
      end

      return M
    '';
  };
}
