# Markup rendering — markview, for reading markdown in the editor.
#
# `icon_provider = "mini"` points markview at the icon set this layer already
# ships rather than letting it load a second one. It is a declared option, so a
# typo is a build error rather than a silent fallback.
#
# Rendering is decoration only: headings, checkboxes, blockquotes, tables and
# fenced-code labels are drawn with extmarks and the buffer text is never
# rewritten. Colours come from the colorscheme, so the render follows an
# appearance flip — verified by capture, where the markdown body changes colour
# between night and day while the plain-text layout stays byte-identical.
#
# Editor-surface states:
#   empty   — a file with no markup gets no decorations at all: a plain text
#             buffer measured zero extmarks, so markview adds nothing rather than
#             adding an empty overlay.
#   partial — at 80 columns a wide table renders inside the window and a long
#             line gets neovim's own `@@@` continuation marker; nothing overlaps.
#   error   — no treesitter parser for the buffer's language means the code-block
#             body renders unhighlighted inside a still-correct block frame.
{ config, lib, ... }:
let
  cfg = config.cvim.ui;
in
{
  config = lib.mkIf (cfg.enable && cfg.markview.enable) {
    plugins.markview = {
      enable = true;
      settings.preview.icon_provider = "mini";

      # The full Obsidian surface — wikilinks, embeds, block refs, tags,
      # highlights, extended checkbox states, callouts, footnotes — ships
      # enabled at the pinned version; verified by extmark count on a file
      # exercising each one. The preset is the one piece that is opt-in: it
      # recolours callout lines to Obsidian's palette. `__raw` because a
      # preset is a lua call, not data.
      settings.markdown.block_quotes.__raw = ''require("markview.presets").block_quotes.obsidian'';
    };

    # How far markview lightens `Normal`'s background per element — lower is
    # dimmer. These are globals, not settings: markview reads them off `vim.g`
    # when it computes its highlight groups, so they survive the day/night
    # flip. markview's own dark branch is 0.15 / 0.15 / 0.2.
    globals = {
      markview_alpha = 0.02;
      markview_code_alpha = 0.02;
      markview_inline_code_alpha = 0.01;
    };

    # The shipped settings as data, for a session that has been experimenting.
    #
    # `markview.setup()` only ever merges (`vim.tbl_deep_extend "force"`), so
    # calling it again cannot take a style back out — the way home is to clear
    # `spec.config` and re-apply what the build passed. `docs/markview-style.md`
    # is where that is spelled as a runnable block.
    #
    # Generated from the EVALUATED attrs rather than from the literal above, so
    # a host that overrides `plugins.markview.settings` through `extendModules`
    # resets to its own config and not to cvim's. A table pasted into the doc
    # instead would be wrong the first time either one changed.
    extraFiles."lua/cvim/markview.lua".text = ''
      --- What cvim configured markview with.
      ---
      --- Generated by modules/ui/markview.nix. Do not edit.
      return {
        settings = ${lib.nixvim.toLuaObject config.plugins.markview.settings},
      }
    '';
  };
}
