# Run the code block under the cursor — `g==` in markdown.
#
# Neovim already ships this idea, for help buffers only:
# `$VIMRUNTIME/ftplugin/help.lua` binds `g==` to execute the `lua` or `vim`
# code block the cursor is in. This is the markdown half, and it keeps the key
# so there is one gesture to learn rather than two.
#
# WHY IN-PROCESS, AND WHY NO PLUGIN. The point of the key is that a block
# changes the editor you are reading it in — apply a markview style, flip an
# option, call an API, and see the result in the same buffer. Every external
# runner (sniprun, mdeval.nvim, code_runner.nvim, molten) evaluates in a
# SEPARATE process and hands back text, which cannot mutate this editor at all.
# So the plugins that look like the answer are the wrong tool, and the right
# one is thirty lines against a treesitter tree.
#
# WHY THE BLOCK IS RESOLVED AT KEYPRESS. help.lua walks the whole buffer at
# FileType time and caches a line -> block table, which goes stale the moment
# the buffer is edited — upstream carries a retry hack for exactly that
# (neovim#36574). Resolving from the cursor node on each press has no cache to
# invalidate, and a doc you are editing while you run it stays correct.
#
# The keymap is written here rather than in the runtime module below so that
# `modules/keymap-guard` can see it: that guard reads `vim.keymap.set(` calls
# out of the generated `init.lua`, and a mapping hidden in `extraFiles` would
# be a mapping it cannot audit.
#
# Editor-surface states:
#   empty   — a markdown buffer with no fenced block: `g==` says so and changes
#             nothing. Same answer with the cursor outside every fence.
#   partial — a fence with no info string, or one this cannot run (```sh):
#             refused BY NAME, so the message says which language it saw. Only
#             `lua`, `vim`, `viml` and `vimscript` run.
#   error   — a block that throws is caught and reported through `vim.notify`;
#             the editor stays up and the buffer is untouched. A block that
#             loops forever hangs THIS editor, because in-process is the whole
#             point — that one costs you the session.
{ config, lib, ... }:
let
  cfg = config.cvim.utilities;
in
{
  config = lib.mkIf cfg.enable {
    extraFiles."lua/cvim/runblock.lua".text = ''
      --- Run the fenced code block under the cursor, in THIS editor.
      ---
      --- Generated by modules/zt/run-code-block.nix. Do not edit.
      local M = {}

      --- What each language means. A table rather than an if-chain because the
      --- refusal message reads the same table: a language absent here is named
      --- back to the user instead of being guessed at.
      local runners = {}

      runners.lua = function(code, chunkname)
        local chunk, syntax_error = load(code, chunkname)
        if not chunk then
          return syntax_error
        end

        local ok, result = pcall(chunk)
        if not ok then
          return result
        end

        -- A block ending in `return something` prints it. That makes the same
        -- key both "apply this" and "show me this" without a second mapping.
        if result ~= nil then
          vim.print(result)
        end
      end

      runners.vim = function(code)
        local ok, err = pcall(vim.api.nvim_exec2, code, { output = false })
        if not ok then
          return err
        end
      end

      runners.viml = runners.vim
      runners.vimscript = runners.vim

      --- The fenced block the cursor is inside, or nil.
      local function block_at_cursor()
        local ok, parser = pcall(vim.treesitter.get_parser, 0, "markdown")
        if not ok or parser == nil then
          return nil
        end

        -- Parse, rather than read whatever tree highlighting happens to have
        -- left behind. A buffer that was just reloaded has no tree yet, and
        -- every lookup into it answers nil — measured, and it is why this does
        -- not use `vim.treesitter.get_node()`, which reads the existing tree.
        local trees = parser:parse(true)
        if trees == nil or trees[1] == nil then
          return nil
        end

        local cursor = vim.api.nvim_win_get_cursor(0)
        local row, col = cursor[1] - 1, cursor[2]

        -- The markdown tree only: an injected lua tree covers the fence body
        -- and knows nothing about the fence around it.
        local node = trees[1]:root():named_descendant_for_range(row, col, row, col)

        while node ~= nil and node:type() ~= "fenced_code_block" do
          node = node:parent()
        end

        if node == nil then
          return nil
        end

        local found = { lnum = node:range() + 1 }

        for child in node:iter_children() do
          local kind = child:type()

          if kind == "info_string" then
            -- First word only: markview's own wiki writes
            -- ```lua from: ../lua/... class: ...` and the rest is metadata.
            found.lang = vim.treesitter.get_node_text(child, 0):match("^%s*([%w_+-]+)")
          elseif kind == "code_fence_content" then
            found.code = vim.treesitter.get_node_text(child, 0)
          end
        end

        return found
      end

      --- `g==`.
      function M.run()
        local found = block_at_cursor()

        if found == nil or found.code == nil then
          vim.notify("runblock: no code block under the cursor", vim.log.levels.WARN)
          return
        end

        local runner = found.lang ~= nil and runners[found.lang] or nil

        if runner == nil then
          vim.notify(
            ("runblock: cannot run a %s block — lua and vim only"):format(found.lang or "language-less"),
            vim.log.levels.WARN
          )
          return
        end

        local err = runner(
          found.code,
          ("@%s block at line %d"):format(vim.api.nvim_buf_get_name(0), found.lnum)
        )

        if err ~= nil then
          vim.notify("runblock: " .. tostring(err), vim.log.levels.ERROR)
        end
      end

      return M
    '';

    autoCmd = [
      {
        event = [ "FileType" ];
        pattern = [ "markdown" ];
        callback.__raw = ''
          function(args)
            vim.keymap.set("n", "g==", function()
              require("cvim.runblock").run()
            end, {
              buffer = args.buf,
              silent = true,
              desc = "Run the code block under the cursor",
            })
          end
        '';
      }
    ];
  };
}
